fabric8io-images/s2i

java/s2i/assemble

@iocanel please merge since CI job will fail

OSFUSE-60: Added back support for .m2/settings.xml

---

java/s2i/assemble

Fixing https://issues.jboss.org/browse/OSFUSE-107

OSFUSE-107: fix quotes in default hawt-app call

---

java/s2i/assemble
karaf/s2i/assemble
sandbox/images/centos7/sti/assemble
sandbox/images/rhel7/sti/assemble
sandbox/templates/sti/assemble
sandbox/templates/sti/assemble-s2i-java-full

@rhuss please verify and merge

OSFUSE-118: Moved custom settings.xml from .m2/ to configuration/

---

java/images/jboss/Dockerfile
java/images/rhel/Dockerfile
java/templates/Dockerfile
karaf/Dockerfile
karaf/Dockerfile.rhel

Relates to: https://bugzilla.redhat.com/show_bug.cgi?id=1365942

Align permissions and user config with other xpaas images

---

java/images/jboss/container-limits
java/images/jboss/java-default-options
java/images/rhel/container-limits
java/images/rhel/java-default-options

which in turn fixes some limit issues

Merged in latest changes from run-java-sh

---

java/images/jboss/README.md
java/images/rhel/README.md
java/templates/README.md
karaf/images/jboss/README.md
karaf/images/rhel/README.md
karaf/templates/README.md
sandbox/images/centos7/README.md
sandbox/images/rhel7/README.md
sandbox/templates/README.md

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Fix various typo

---

java/fish-pepper.yml
java/images.yml
java/images/jboss/Dockerfile
java/images/rhel/README.md
java/templates/Dockerfile
java/templates/README.md
karaf/fish-pepper.yml
karaf/images.yml
karaf/images/jboss/Dockerfile
karaf/images/jboss/README.md
karaf/images/jboss/s2i/run
karaf/images/rhel/Dockerfile
karaf/images/rhel/s2i/run

This will also update the upstream s2i images on Docker Hub

Prepare for release 2.0.2

---

java/blocks/jmxexporter/fp-files/prometheus-opts
java/blocks/jmxexporter/install.dck
java/images.yml
java/images/jboss/Dockerfile
java/images/jboss/prometheus-config.yml
java/images/jboss/prometheus-opts
java/images/jboss/s2i/run
java/images/rhel/Dockerfile
java/images/rhel/prometheus-config.yml
java/images/rhel/prometheus-opts
java/images/rhel/s2i/run
java/templates/Dockerfile
java/templates/s2i/run
karaf/blocks/jmxexporter/fp-files/prometheus-opts
karaf/blocks/jmxexporter/install.dck
karaf/images.yml
karaf/images/jboss/Dockerfile
karaf/images/jboss/prometheus-config.yml
karaf/images/jboss/prometheus-opts
karaf/images/jboss/s2i/run
karaf/images/rhel/Dockerfile
karaf/images/rhel/prometheus-config.yml
karaf/images/rhel/prometheus-opts
karaf/images/rhel/s2i/run
karaf/templates/Dockerfile
karaf/templates/s2i/run

Add prometheus as a javaagent, add config and script support for prometheus

Add prometheus as a javaagent, add config and script support for prometheus

---

java/images/rhel/Dockerfile
java/templates/Dockerfile
karaf/images/jboss/Dockerfile
karaf/images/rhel/Dockerfile
karaf/templates/Dockerfile

https://issues.jboss.org/browse/OSFUSE-679

OSFUSE-679: Allow Karaf startup script to access /home/jboss

---

java/example/.s2i/environment
java/example/README.md
java/example/pom.xml
java/example/src/main/java/ch/vorburger/openshift/s2i/example/Server.java
java/example/src/test/java/ch/vorburger/openshift/s2i/example/ServerTest.java
test.sh

this example originally was at
https://github.com/vorburger/s2i-java-example

add java example and test.sh (#120)

---

java/images/rhel/Dockerfile
karaf/images/rhel/Dockerfile

Use jolokia 1.5.0 community version.

Use jolokia 1.5.0 community version.

---

java/images/jboss/Dockerfile
java/images/jboss/apache_software_license_version_2.0-apache-2.0.txt
java/images/jboss/licenses.css
java/images/jboss/licenses.html
java/images/jboss/licenses.xml
java/images/rhel/Dockerfile
java/images/rhel/apache_software_license_version_2.0-apache-2.0.txt
java/images/rhel/licenses.css
java/images/rhel/licenses.html
java/images/rhel/licenses.xml
java/templates/Dockerfile
java/templates/licenses.html
java/templates/licenses.xml
karaf/images/jboss/Dockerfile
karaf/images/jboss/apache_software_license_version_2.0-apache-2.0.txt
karaf/images/jboss/licenses.css
karaf/images/jboss/licenses.html
karaf/images/jboss/licenses.xml
karaf/images/rhel/Dockerfile
karaf/images/rhel/apache_software_license_version_2.0-apache-2.0.txt
karaf/images/rhel/licenses.css
karaf/images/rhel/licenses.html
karaf/images/rhel/licenses.xml
karaf/templates/Dockerfile
karaf/templates/licenses.html
karaf/templates/licenses.xml

https://issues.jboss.org/browse/ENTESB-6909

ENTESB-6909 Add licenses.xml to FIS images

---

java/images.yml
java/images/centos/Dockerfile
java/images/rhel/Dockerfile
java/templates/Dockerfile

fix: Set working directory back to /home/jboss

---

java/blocks/jmxexporter/fp-files/prometheus-config.yml
java/images/centos/prometheus-config.yml
java/images/rhel/prometheus-config.yml
karaf/blocks/jmxexporter/fp-files/prometheus-config.yml
karaf/images/centos/prometheus-config.yml
karaf/images/rhel/prometheus-config.yml

Add LastProcessingTime and DeltaProcessingTime to Prometheus Metrics

ENTESB-9524 Add LastProcessingTime and DeltaProcessingTime to Prometheus Metrics

---

test.sh

This will allow to easily test no just the current
centos image but also a fedora variant and Java 11 version.
(It could also be used to self test that RHEL variant.)

make image to test flexible in test.sh (#160)

---

java/blocks/jmxexporter/fp-files/prometheus-config.yml
karaf/blocks/jmxexporter/fp-files/prometheus-config.yml

Fix JMX exporter quoted property values captured incorrectly

---

test.sh

Inspired by #212 and found this very useful for #213.

show docker logs in case of test failure

---

java/images.yml
karaf/images.yml

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Remove "productized" comments from community branch #220

---

java/blocks/jmxexporter/install.dck
java/blocks/jolokia/install.dck
java/images/centos-java11/Dockerfile
java/images/centos/Dockerfile
java/images/fedora-java11/Dockerfile
java/images/rhel/Dockerfile
karaf/blocks/jmxexporter/install.dck
karaf/blocks/jolokia/install.dck
karaf/images/centos/Dockerfile
karaf/images/rhel/Dockerfile

update Maven central repository URL

---

java/images.yml
java/images/centos-java11/Dockerfile
java/images/centos-java11/README.md
java/images/centos-java11/licenses.html
java/images/centos-java11/licenses.xml
java/images/centos/README.md
java/images/fedora-java11/Dockerfile
java/images/fedora-java11/licenses.html
java/images/fedora-java11/licenses.xml

* also update CentOS 7 version description

update to latest Maven 3.6.3

---

java/templates/README.md

@rhuss I saw you already made a PR for the fishpepper build. Here's the explanation.

Add build time maven server config explanation

---

java/blocks/jmxexporter/fp-files/prometheus-config.yml
java/images/centos-java11/prometheus-config.yml
java/images/centos/prometheus-config.yml
java/images/fedora-java11/prometheus-config.yml
karaf/blocks/jmxexporter/fp-files/prometheus-config.yml
karaf/images/centos/prometheus-config.yml

Fix metric types: ExchangesInflight -> GAUGE, Redeliveries -> COUNTER in prometheus config

---

java/blocks/jmxexporter/fp-files/prometheus-config.yml
java/images/rhel/prometheus-config.yml
karaf/blocks/jmxexporter/fp-files/prometheus-config.yml
karaf/images/rhel/prometheus-config.yml

Fix metric types: ExchangesInflight -> GAUGE, Redeliveries -> COUNTER in prometheus config (Fuse 7.x)
